# Generated by Django 2.2 on 2021-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210512_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='product_pictures', to='products.Picture'),
        ),
    ]
